<!DOCTYPE html>
<!--[if IE 7]>  <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>  <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en">
	<head>
		<!-- TITLE OF SITE -->
		<title>Parejas en Cuba | Piropazo</title>

		<!-- Meta -->
		<meta charset="utf-8">
		<meta name="description" content="Conoce mujeres y chicos en Cuba y encuentra el amor y la amistad. Tenemos la red de busqueda de parejas mas grande de Cuba, para chat con Cubanos dentro y fuera de Cuba." />
		<meta name="keywords" content="piropazo, chat cubano,chat con cubanos,conocer mujeres en cuba,chat de cuba,chat cubano chat cuba,amigos cubanos,conocer gente en Cuba,conocer cubanas,conocer mujeres de cuba,contactos con cubanas,contactos cubanas,contacto con mujeres cubanas" />
		<meta name="developer" content="salvi@apretaste.com">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

		<!-- FAV AND TOUCH ICONS   -->
		<link rel="icon" type="image/png" href="images/apple-touch-icon.png" />
		<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
		<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
	</head>
	<body>
		<!-- Start: Navbar Area
		============================= -->
		<header id="header" class="okayNav-header navbar-fixed-top main-navbar-top">
			<div class="container">
				<div class="row">

					<div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">

						<!-- TEMPLATE LOGO LIGHT -->
						<a class="navbar-brand light-logo" href="index.php"><img src="images/logo-color.png" alt="Parejas en Cuba" class="img-responsive"></a>

					</div> <!-- End: .col-xs-3 -->
					<div class="col-lg-9 col-md-9 col-sm-9 col-xs-6">

						<nav role="navigation" class="okayNav pull-right" id="js-navbar-menu">
							<ul id="navbar-nav" class="navbar-nav">
								<li><a class="btn-nav" href="#features">Caracter&iacute;sticas</a></li>
								<li><a class="btn-nav" href="#how-it-works">&iquest;C&oacute;mo trabaja?</a></li>
								<li><a class="btn-nav" href="#describe">Tecnolog&iacute;a</a></li>
							   <li><a class="btn-nav" href="#subscribe">Suscr&iacute;base</a></li>
								<li><a class="btn-nav" href="#screenshots">Pantallazos</a></li>
								<li><a class="btn-nav" href="#download">Descargar</a></li>
							</ul>
						</nav>

					</div> <!-- End: .col-xs-9 -->
				</div> <!-- End: .row -->
			</div> <!-- End: .container -->
		</header><!-- /header -->
		<!-- End: Navbar Area
		============================= -->


		<!-- Start: Header Section
		================================ -->
		<section class="header-section-1 bg-1 header-js" id="header" >
			<div class="overlay-color">
				<div class="container">
					<div class="row section-separator sp-top">

						<div class="part-1 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
							<div class="part-inner text-center mr-small">

								<!-- Main Logo -->
								<a href="index.php" class="logo-link">
									<img src="images/logo-color.png" alt="Parejas en Cuba" class="img-responsive logo">
								</a>

								<!--  Header SubTitle Goes here -->
								<h1 class="title">La red de parejas más grande de Cuba.</h1>

								<!-- Button Area -->
								<div class="btn-form m-t-40">
									<a href="#download" class="btn btn-fill btn-scroll">Descargar App</a>
									<a href="https://apretaste.com/piropazo" target="_blank" class="btn btn-border">Versi&oacute;n Web</a>
								</div>

								<!-- Mobile App Image -->
								<div class="image-group">
									<img src="images/home-left.png" alt="Parejas en Cuba" class="home-left img-responsive">
									<img src="images/home-center.png" alt="Parejas en Cuba" class="home-center img-responsive">
									<img src="images/home-right.png" alt="Parejas en Cuba" class="home-right img-responsive">
								</div>

							</div>
						</div> <!-- End: .part-1 -->

					</div> <!-- End: .row -->
				</div> <!-- End: .container -->
			</div> <!-- End: .overlay-color -->
		</section>
		<!-- End: Header Section
		================================ -->



		<!-- Start: Features Section 1
		================================== -->
		<section class="features-section-1 section" id="features">
			<div class="container">
				<div class="row section-separator">

					<!-- Start: Section Heading -->
					<div class="section-header col-md-10 col-md-offset-1">
						<h2 class="section-heading">Caracter&iacute;sticas</h2>
						<p class="sub-title">Hay muchas apps para citas. &iquest;Sabes que nos hace especial?</p>
					</div>
					<!-- End: Section Heading -->

					<div class="part-1 col-xs-12">
						<div class="row">

							<div class="vertical-middle col-md-4 col-sm-6 col-sm-offset-3 ">

								<!-- Each Features Item -->
								<div class="feature-item text-center">

									<div class="gradient-border">
										<i class="icon features-icon gradient-text icon-icon-like"></i>
									</div>

									<div class="feature-content text-center">
										<h3 class="title">Di S&iacute; o No</h3>
										<p>Dale S&iacute; cuando te guste alguien, o dile que No para seguir viendo otras personas.</p>
									</div>

								</div> <!-- End: .feature-item -->

								<!-- Each Features Item -->
								<div class="feature-item text-center">

									<div class="gradient-border">
										<i class="icon features-icon gradient-text icon-icon-heart-alt"></i>
									</div>

									<div class="feature-content text-center">
										<h3 class="title">Env&iacute;a Flores</h3>
										<p>Env&iacute;a flores a quienes de verdad te gusten, para asegurarte que nunca pasar&aacute;s desapercibido.</p>
									</div>

								</div> <!-- End: .feature-item -->

							</div> <!-- End: .col-md-4 -->

							<div class="vertical-middle col-md-4">

								<!-- Features Image  -->
								<div class="features-image">

									<img src="images/feature-phone.png" alt="Parejas en Cuba">

								</div>  <!-- End: .features-image  -->

							</div> <!-- End: .col-md-4 -->

							<div class="vertical-middle col-md-4 col-sm-6 col-sm-offset-3">

								<!-- Each Features Item -->
								<div class="feature-item text-center">

									<div class="gradient-border">
										<i class="icon features-icon gradient-text icon-icon-star-alt"></i>
									</div>

									<div class="feature-content text-center">
										<h3 class="title">Cor&oacute;nate Rey o Reina</h3>
										<p>Ponte una corona para que tu perfil se muestre con mucha mas frecuencia a otros.</p>
									</div>

								</div> <!-- End: .feature-item -->

								<!-- Each Features Item -->
								<div class="feature-item text-center">

									<div class="gradient-border">
										<i class="icon features-icon gradient-text icon-icon-chat-alt"></i>
									</div>

									<div class="feature-content text-center">
										<h3 class="title">Habla con tus Citas</h3>
										<p>Una vez que ambos digan S&iacute;, habla con tus parejas y encuentra a tu media naranja.</p>
									</div>

								</div> <!-- End: .feature-item -->

							</div> <!-- End: .col-md-4 -->

						</div> <!-- End: .row -->
					</div> <!-- End: .part-1 -->

				</div> <!-- End: .row -->
			</div> <!-- End: .container -->
		</section>
		<!-- End: Features Section 1
		================================== -->




		<!-- Start: Features Section 2
		================================== -->
		<section class="features-section-2 bg-2 section" id="how-it-works">
			<div class="overlay-color">
				<div class="container">
					<div class="row section-separator light-text">

						<!-- Start: Section Heading -->
						<div class="section-header col-md-10 col-md-offset-1">
							<h2 class="section-heading">&iquest;C&oacute;mo trabaja?</h2>
							<p class="sub-title">Aprende como Piropazo trabaja en cuatro simples pasos</p>
						</div>
						<!-- End: Section Heading -->

						<div class="part-1 col-xs-12">
							<div class="row">

								<div class="features-item text-center col-sm-3 col-xs-12">

									<div class="icon-outer">
										<i class="icon features-icon gradient-text-full icon-icon-profile"></i>
									</div>

									<h4 class="title m-t-30">Cr&eacute;ate un perfil</h4>

								</div>
								<div class="features-item text-center col-sm-3 col-xs-12">

									<div class="icon-outer">
										<i class="icon features-icon gradient-text-full icon-icon-like"></i>
									</div>

									<h4 class="title m-t-30">Di S&iacute; a otros usuarios</h4>

								</div>
								<div class="features-item text-center col-sm-3 col-xs-12">

									<div class="icon-outer">
										<i class="icon features-icon gradient-text-full icon-icon-check"></i>
									</div>

									<h4 class="title m-t-30">Espera que te digan S&iacute;</h4>

								</div>
								<div class="features-item text-center col-sm-3 col-xs-12">

									<div class="icon-outer">
										<i class="icon features-icon gradient-text-full icon-icon-chat-alt"></i>
									</div>

									<h4 class="title m-t-30">Habla con tu parejas</h4>

								</div>

							</div> <!-- End: .row -->
						</div> <!-- End: .part-1 -->

					</div> <!-- End: .row -->
				</div> <!-- End: .container -->
			</div>
		</section>
		<!-- End: Features Section 2
		================================== -->




		<!-- Start: Features Section 3
		================================== -->
		<section class="features-section-3 section bg-dark" id="describe">
			<div class="container">
				<div class="row section-separator">

					<div class="features-image col-md-6 col-md-push-6">

						<img src="images/2-phone-right.png" alt="App Picture" class="img-responsive pull-right">

					</div>
					<div class="features-content m-t-50 col-md-6 col-md-pull-6">

						<!-- Start: Section Heading -->
						<div class="section-header text-left m-b-30">
							<h2 class="section-heading gradient-text-full">Alta Tecnolog&iacute;a</h2>
						</div>
						<!-- End: Section Heading -->

						<div class="detail">
							<p>Conectamos miles de usuarios en Cuba gracias a una <a target="_blank" href="https://apretaste.com/bienvenido">innovativa tecnolog&iacute;a</a> que les permite revisar Piropazo desde su email, sin tener acceso a la web. Gracias a esta sistema (que desarrollamos y mantenemos), podemos conectarte a la red de Cubanos dentro de Cuba m&aacute;s grande para buscar parejas.</p>
						</div> <!-- End: .detail -->

						<!-- Button Area -->
						<div class="btn-form m-t-50">
							<a href="#download" class="btn btn-fill btn-scroll">Descargar App</a>
<!--
							<a href="mailto:apretaste@gmail.com?subject=piropazo" class="btn btn-icon left-icon btn-border">
								<i class="icon icon-icon-mail-alt"></i>
								<span class="btn-text">Versi&oacute;n Email</span>
							</a>
-->
						</div>
					</div> <!-- End: .features-content -->
				</div> <!-- End: .row -->
			</div> <!-- End: .container -->
		</section>
		<!-- End: Features Section 3
		================================== -->



		<!-- Start: Section Separator
		================================== -->
		<section class="Section-separator">
			<div class="container">

				<hr class="section-separator-line"> <!-- Separatior Two Section -->

			</div> <!-- End: .container -->
		</section>
		<!-- End: Section Separator
		================================== -->



		<!-- Start: Features Section 3
		================================== -->
		<section class="features-section-3 section" id="describe-2">
			<div class="container">
				<div class="row section-separator">

					<div class="features-image col-md-6">

						<img src="images/2-phone-left.png" alt="App Image" class="img-responsive pull-left">

					</div>
					<div class="features-content m-t-50 col-md-6 ">

						<!-- Start: Section Heading -->
						<div class="section-header text-left m-b-30">
							<h2 class="section-heading gradient-text-full">Un viaje diferente</h2>
						</div>
						<!-- End: Section Heading -->

						<div class="detail">
							<p>¿Es Cuba el lugar que siempre has soñado visitar? Piropazo puede cambiar la forma que disfrutes tu próximo viaje a la isla, conectándote a gente emocionante y aventurezca.</p>
						</div> <!-- End: .detail -->

						<div class="row features-list">

							<div class="col-sm-6">
								<div class="media">
									<div class="media-left">
										<i class="icon gradient-text-full icon-icon-globe"></i>
									</div>
									<div class="media-body">
										<h5 class="title">50K+ Usuarios</h5>
										<p>M&aacute;s de 50,000 Cubanos ya est&aacute;n usando Piropazo.</p>
									</div>
								</div> <!-- End: .melia -->
							</div>
							<div class="col-sm-6">
								<div class="media">
									<div class="media-left">
										<i class="icon gradient-text-full icon-icon-cloud-download-alt"></i>
									</div>
									<div class="media-body">
										<h5 class="title">Descarga Gratis</h5>
										<p>Descargar y usa Piropazo gratis, dentro o fuera de Cuba.</p>
									</div>
								</div> <!-- End: .melia -->
							</div>
							<div class="col-sm-6">
								<div class="media">
									<div class="media-left">
										<i class="icon gradient-text-full icon-icon-puzzle"></i>
									</div>
									<div class="media-body">
										<h5 class="title">F&aacute;cil de usar</h5>
										<p>Piropazo es simple de aprender y super divertido de usar.</p>
									</div>
								</div> <!-- End: .melia -->
							</div>
							<div class="col-sm-6">
								<div class="media">
									<div class="media-left">
										<i class="icon gradient-text-full icon-icon-cart-alt"></i>
									</div>
									<div class="media-body">
										<h5 class="title">Flores y Coronas</h5>
										<p>Compra en nuestra y tienda saca m&aacute;ximo provecho.</p>
									</div>
								</div> <!-- End: .melia -->
							</div>

						</div> <!-- End: .row -->

					</div> <!-- End: .features-content -->

				</div> <!-- End: .row -->
			</div> <!-- End: .container -->
		</section>
		<!-- End: Features Section 3
		================================== -->




		<!-- Start: Features Section 4
		================================== -->
		<section class="features-section-4 section bg-3" id="subscribe">
			<div class="overlay-color">
				<div class="container">
					<div class="row section-separator light-text">

						<!-- Start: Section Heading -->
						<div class="section-header col-md-10 col-md-offset-1">
							<h2 class="section-heading">&iexcl;&Uacute;nete a la lista!</h2>
							<p class="sub-title">D&eacute;janos tu email y te mantendremos al d&iacute;a de novedades de nuestra red.</p>
						</div>
						<!-- End: Section Heading -->

						<div class="part-1 col-sm-6 col-sm-offset-3 col-xs-12">
							<div class="row">
								<div class="col-md-10 col-md-offset-1">
									<!-- Local Subscriber Form Goes Here  -->
									<form id="local-subscribe" method="post" class="single-form text-center col-sm-10 col-sm-offset-1 col-xs-12">
										<div class="container-fluid">
											<p class="subscription-success"><i class="fa fa-check-circle"></i>Gracias por suscribirte. Ahora formas parte de nuestra red.</p>
											<p class="subscription-failed"><i class="fa fa-times-circle"></i>Tuvimos un error subscribi&eacute;ndole.</p>

											<div class="row">
												<div class="input-group">
													<input type="email" id="subscriber-email" name="email" placeholder="usuario@correo.com" class="form-control">
													<div class="input-group-btn">
														<button class="btn btn-fill">SUSCRIBIRSE</button>
													</div>
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</section>
		<!-- End: Features Section 4
		================================== -->




		<!-- Start: Features Section 3
		================================== -->
		<section class="features-section-3 section app-swiper-slide" id="screenshots">
			<div class="container">
				<div class="row section-separator">

					<div class="features-content m-t-50 col-md-6">

						<!-- Start: Section Heading -->
						<div class="section-header text-left m-b-30">
							<h2 class="section-heading gradient-text-full">Pantallazos</h2>
						</div>
						<!-- End: Section Heading -->

						<div class="detail">
							<p>Sum&eacute;rgete en Piropazo incluso antes de descargarlo y aprende como se usa con los siguientes ejemplos de pantallas.</p>
						</div> <!-- End: .detail -->

						<!-- Button Area -->
						<div class="btn-form m-t-40 btn-scroll">
							<a href="#download" class="btn btn-fill">Descargar App</a>
						</div>

					</div> <!-- End: .features-content -->
					<div class="col-md-6">
						<div class="swiper-container screenshots-thumb">
							<div class="swiper-wrapper">

								<div class="swiper-slide">
									<div class="item"><img src="images/app-screenshots/1.png" alt="Parejas en Cuba"></div>
								</div>

								<div class="swiper-slide">
									<div class="item"><img src="images/app-screenshots/2.png" alt="Parejas en Cuba"></div>
								</div>

								<div class="swiper-slide">
									<div class="item"><img src="images/app-screenshots/3.png" alt="Parejas en Cuba"></div>
								</div>

								<div class="swiper-slide">
									<div class="item"><img src="images/app-screenshots/4.png" alt="Parejas en Cuba"></div>
								</div>

								<div class="swiper-slide">
									<div class="item"><img src="images/app-screenshots/5.png" alt="Parejas en Cuba"></div>
								</div>
							</div>
						</div> <!-- End: .testimonials-thumb -->
					</div> <!-- End: .col-sm-6 -->

				</div> <!-- End: .row -->

			</div> <!-- End: .container -->
		</section>
		<!-- End: Features Section 3
		================================== -->




		<!-- Start: Features Section 5
		================================== -->
		<section class="features-section-5 testimonials-1 bg-4 section" id="download">
			<div class="overlay-color">
				<div class="container">
					<div class="row section-separator light-text">

						<!-- Start: Section Heading -->
						<div class="section-header col-md-10 col-md-offset-1">
							<h2 class="section-heading">Descarga Piropazo</h2>
							<p class="sub-title">&iexcl;S&uacute;mate a m&aacute;s de 100,000 Cubanos usando Piropazo!</p>
						</div>
						<!-- End: Section Heading -->

						<div class="clearfix"></div>

						 <!-- Start: Download Button -->
						<div class="btn-form text-center">
							<a href="https://itunes.apple.com/US/app/id1246204860" class="btn btn-icon left-icon btn-fill">
								<i class="icon icon-app-store"></i>
								<span class="btn-text">iTunes</span>
							</a>

							<a href="https://play.google.com/store/apps/details?id=com.apretaste.piropazo" class="btn btn-icon left-icon btn-fill">
								<i class="icon icon-google-play"></i>
								<span class="btn-text">Play Store</span>
							</a>

							<a href="https://apretaste.com/piropazo" target="_blank" class="btn btn-icon left-icon btn-border">
								<i class="icon icon-icon-globe"></i>
								<span class="btn-text">Versi&oacute;n Web</span>
							</a>
						</div>
						<!-- End: Download Button -->

						<div class="clearfix"></div>

						<div class=" col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
							<div class="swiper-container">
								<div class="swiper-wrapper">

									<!-- SLIDES -->
									<div class="swiper-slide">
										<blockquote>“Piropazo es en serio la red más grande que he visto de parejas en Cuba. Si estás buscando tu próxima aventura loca, o el amor de su vida, de verdad es perfecto para tí, Hay de todo un poco.”</blockquote>
										<p class="client-profile">
											<img src="images/clients-pic/client-1.png" alt="Parejas en Cuba" class="client-img img-responsive">
											<span class="detail-group text-left">
												<span class="name">Juan Cruz</span>
												<span class="position">Febrero 10, 2017</span>
											</span>
										</p>
									</div> <!-- End: .swioer-slide -->

									<div class="swiper-slide">
										<blockquote>“Parece imposible conocer gente en Cuba a través de una app, como si vivieran en otro lugar del mundo. Me he vuelto una fanática de Piropazo, y lo uso como otra red social. ¡Gracias!”.</blockquote>
										<p class="client-profile">
											<img src="images/clients-pic/client-2.png" alt="Parejas en Cuba" class="client-img img-responsive">
											<span class="detail-group text-left">
												<span class="name">Julia Fuentes</span>
												<span class="position">Febrero 12, 2017</span>
											</span>
										</p>
									</div> <!-- End: .swioer-slide -->

									<div class="swiper-slide">
										<blockquote>“Gracias a Piropazo he conocido a alguien fenomenal que ha cambiado mi vida. Es una app que vale le pena usar si quiere darle un giro a su vida y conocer gente marvillosa.”</blockquote>
										<p class="client-profile">
											<img src="images/clients-pic/client-3.png" alt="Parejas en Cuba" class="client-img img-responsive">
											<span class="detail-group text-left">
												<span class="name">Pedro Ledezmo</span>
												<span class="position">Febrero 2, 2017</span>
											</span>
										</p>
									</div> <!-- End: .swioer-slide -->

								</div>
							</div> <!-- /#testimonials-1 -->
						</div> <!-- End: .col-xs-12 -->

					</div> <!-- End: .row -->
				</div> <!-- End: .container -->
			</div> <!-- End: .overlay-color-full -->
		</section>
		<!-- End: Features Section 5
		================================== -->




		<!-- Start: Footer Section 1
		================================== -->
		<footer class="footer-section-1" id="footer">
			<div class="container">
				<div class="row section-separator">
					<div class="col-sm-12 text-center">
						<a href="index.php" class="logo-link">
							<img style="width:50px;" src="images/logo-color.png" alt="Parejas en Cuba" class="img-responsive logo">
						</a>
						<p class="sub-title">&iquest;Tienes Preguntas?</p>
						<p><a href="mailto:soporte@apretaste.com">soporte@apretaste.com</a></p>
						<a href="https://www.facebook.com/piropazo"><i class="icon icon-social-facebook"></i></a>
						<a href="https://twitter.com/piropazocuba"><i class="icon icon-social-twitter"></i></a>
						<a href="https://instagram.com/apretaste"><i class="icon icon-social-instagram"></i></a>
					</div>
				</div><!-- End: .section-separator  -->
			</div> <!-- End: .container  -->
		</footer>
		<!-- End: Footer Section 1
		================================== -->

		<!-- CSS
		========================================-->
		<link href="<?=$min->minify('css/bootstrap.min.css');?>" rel="stylesheet" type="text/css" />
		<link href="<?=$min->minify('css/responsive.css');?>" rel="stylesheet" type="text/css" />
		<link href="<?=$min->minify('css/style.css');?>" rel="stylesheet" type="text/css" />
		<link href="<?=$min->minify('css/styles.css');?>" rel="stylesheet" type="text/css" />
		<link href="<?=$min->minify('css/plagin.css');?>" rel="stylesheet" type="text/css" />
		<link href="<?=$min->minify('css/color-1.css');?>" rel="stylesheet" type="text/css" />
		<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600' rel='stylesheet' type='text/css'>

		<!-- SCRIPTS
		========================================-->
		<script src="<?=$min->minify('js/jquery-1.11.3.js');?>"></script>
		<script src="<?=$min->minify('js/bootstrap.min.js');?>"></script>
		<script src="<?=$min->minify('js/plagin.js');?>"></script>
		<script src="<?=$min->minify('js/custom-scripts.js');?>"></script>
		<!--[if lt IE 9]>
			<script src="<?=$min->minify('js/html5shiv.js');?>"></script>
			<script src="<?=$min->minify('js/respond.min.js');?>"></script>
		<![endif]-->

		<!-- Google Analytics Tracking
		==========================================-->
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-93477066-1', 'auto');
		  ga('send', 'pageview');
		</script>
	</body>
</html>
